name: CI-iOS
on:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - main
      - dev

env:
  VERBOSE: 1
  BUILD_DIR: ./test_repo/build

jobs:
  Test_iOS:
    name: ${{matrix.os}} ${{matrix.build_type}} ${{matrix.packaging_maintainer_mode == 'ON' && '(maintainer mode)' || ''}}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        build_type:
          - Release
          - Debug
        packaging_maintainer_mode:
          - ON
        is_tagged:
          - ${{ startsWith(github.ref, 'refs/tags/') }}

        include:          
          - build_type: Release
            enable_ipo: On

        exclude:
          # Exclude Debug builds if tag is present - we aare packaging only release builds
          - is_tagged: true
            build_type: Debug
          
          # Exclude Release builds if tag is not present
          - is_tagged: false
            build_type: Release  

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -S ./test_repo -B ${{ env.BUILD_DIR }} \
            -G "Xcode" \
            -DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain/ios.toolchain.cmake \
            -D${{ env.PROJECT_NAME }}_ENABLE_IPO=${{matrix.enable_ipo }} \
            -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} \
            -D${{ env.PROJECT_NAME }}_PACKAGING_MAINTAINER_MODE:BOOL=${{matrix.packaging_maintainer_mode}} \
            -D${{ env.PROJECT_NAME }}_ENABLE_COVERAGE:BOOL=${{ matrix.build_type == 'Debug' }} \
            -DGIT_SHA:STRING=${{ github.sha }} \
            -DPLATFORM=OS64COMBINED \
            -DDEPLOYMENT_TARGET=13.0

      - name: Build
        run: |
          cmake --build ${{ env.BUILD_DIR }} --config ${{matrix.build_type}}

      - name: Publish Tagged Release
        uses: softprops/action-gh-release@v2
        if: ${{ matrix.is_tagged && matrix.build_type == 'Release' }}
        with:
          token: ${{ secrets.GH_PAT }}
          files: |
            ${{ env.BUILD_DIR }}/*-*${{ matrix.build_type }}*-*.*
