name: CI-iOS
on:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - main
      - dev

jobs:
  Test_iOS:
    name: ${{matrix.os}} ${{matrix.build_type}} ${{matrix.packaging_maintainer_mode == 'ON' && '(maintainer mode)' || ''}}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        build_type:
          - Release
          - Debug
        packaging_maintainer_mode:
          - ON
        build_shared_libs:
          # - ON
          - OFF
        is_tagged:
          - ${{ startsWith(github.ref, 'refs/tags/') }}

        exclude:
          # Exclude Debug builds if tag is present - we aare packaging only release builds
          - is_tagged: true
            build_type: Debug
          
          # Exclude Release builds if tag is not present
          - is_tagged: false
            build_type: Release  

    steps:
      - uses: actions/checkout@v4
      
      - name: Load Constants
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.github/constants.env'

      - name: Configure CMake
        run: |
          ./scripts/make_iOS.sh \
            --build-type ${{matrix.build_type}} \
            --maintainer-mode ${{matrix.packaging_maintainer_mode}} \
            --git-sha ${{ github.sha }} \
            --enable-code-coverage ${{ matrix.build_type == 'Debug' }} \
            --build-dir ${{ env.BUILD_DIR }}

      - name: CPack
        if: matrix.build_type == 'Release'
        working-directory: ${{ env.BUILD_DIR }}
        run: |
            cpack -C ${{matrix.build_type}} -G ${{ contains(matrix.os, 'windows') && 'ZIP' || 'TBZ2' }}
 
      - name: Publish Tagged Release
        uses: softprops/action-gh-release@v2
        if: ${{ matrix.is_tagged && matrix.build_type == 'Release' }}
        with:
          token: ${{ secrets.GH_PAT }}
          files: |
            ${{ env.BUILD_DIR }}/*-*${{ matrix.build_type }}*-*.*
