name: CI-macos
on:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - main
      - dev

jobs:
  TEST-MACOS:
    name: ${{matrix.os}} ${{matrix.build_type}} ${{matrix.packaging_maintainer_mode == 'ON' && '(maintainer mode)' || ''}}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        build_type:
          - Release
        packaging_maintainer_mode:
          - ON
        enable_ipo:
          - OFF
        build_shared_libs:
          # - ON
          - OFF
        is_tagged:
          - ${{ startsWith(github.ref, 'refs/tags/') }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Load Constants
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.github/constants.env'

      - name: Configure CMake
        run: |
          brew install eigen
          ./scripts/install_deps_macos.sh
          ./make_macOS.sh