name: CI-macos
on:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - main
      - dev

jobs:
  TEST-MACOS:
    name: ${{matrix.os}} ${{matrix.build_type}} ${{matrix.packaging_maintainer_mode == 'ON' && '(maintainer mode)' || ''}}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        build_type:
          - Release
        packaging_maintainer_mode:
          - ON
        enable_ipo:
          - OFF
        build_shared_libs:
          # - ON
          - OFF
        is_tagged:
          - ${{ startsWith(github.ref, 'refs/tags/') }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Load Constants
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.github/constants.env'

      # - name: Configure CMake
      #   run: |
      #     brew install eigen
      #     ./scripts/install_deps_macos.sh
      
      # - name: Upload Built Library
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: opencvlibs
      #     path: ./install/macOS/opencv
      
      - name: Configure CMake
        run: |
          brew install eigen
          ./scripts/make_macOS.sh

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'

      - name : Install dependencies
        run: |
          cd blabla
          flutter pub get
          dart run ffigen --config ffigen.yaml

      - name: install app
        run: |
          cd app
          flutter pub get
          flutter build ios --release --verbose --no-codesign