name: Test Windows Signing

on:
  push:
    paths:
      - 'scripts/sign_windows.ps1'
      - '.github/workflows/test-windows-signing.yml'
  pull_request:
    paths:
      - 'scripts/sign_windows.ps1'
      - '.github/workflows/test-windows-signing.yml'
  workflow_dispatch:

jobs:
  test-signing:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          New-Item -ItemType Directory -Path "test-signing" -Force
          "This is a test file" | Out-File -FilePath "test-signing/test.exe" -Encoding ASCII

      - name: Test signing script
        env:
          SM_HOST: ${{ secrets.SM_HOST }}
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_FILE: ${{ secrets.SM_CLIENT_CERT_FILE }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
          SM_CODE_SIGNING_CERT_SHA1_HASH: ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }}
          SM_CERTIFICATE_CONTENT: ${{ secrets.SM_CERTIFICATE_CONTENT }}
          SM_CERT_ALIAS: ${{ secrets.SM_CERT_ALIAS }}
        run: |
          .\scripts\sign_windows.ps1 -InputPath "test-signing" -ForceKSPSetup 